### ISSUE TITLE
BRS-013 Disconnect/re-connect metering points

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/geh-metering-point#243]
**Description**

A grid company sends in a request because they want to change the connection status for a metering point. Datahub validates the message and either accepts or rejects the message. If a request is accepted the connection status is changed. The balance supplier is informed about the change in connection state. 

**Acceptance criteria**

- [x] A grid company can request and update connection status for all metering point types
- [x] A grid company can receive accept/reject messages for their request
- [x] The connection status can be changed for all metering point types
- [ ] A balance supplier can receive information about the connection status for changed metering points 

The team assessment is that it will take 2 developers  2 sprints to complete this feature. 

**Test flow**
A grid company sends in a request for change connection status for a metering point. DH processes the request and either accepts or rejects the request. A message informing the balance supplier about change in connection status for a MP is sent to the balance supplier. And other domains are informed via integration event.

_Scenarios_

- A grid company sends in a request for change connection status for a metering point. The request is accepted and a accept message is created and sent to the grid company.
- A grid company sends in a request for change connection status for a metering point. The request is rejected and a message is created and sent to the grid company.
- When a request for change connection status has been approved a message containing information about change in connection status is created and sent to the balance supplier.
- When the connection status for a metering point has changed, the information is published to an integration event so the information is accessible for other domains.
