### ISSUE TITLE
Grid areas

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/geh-metering-point#250]
### Description
The purpose of this feature is to be able to create, merge and close down grid areas. 
Grid areas are a pivotal part of the system. It is the grid companies who owns grid areas.
A grid area consist of a number (large number) of metering points. 
It is the TSO that creates, merges and closes down grid areas on behalf of the grid company. 
It is important to mention that it is ONLY the TSO that can initiate the action. 
There are three overall scenarios: Create, merge and close down grid areas.

### Acceptance criteria
- [ ] It must be possible to create a new grid area
- [ ] The model should enable merge of grid areas
- [ ] The model should enable close down of grid areas

**Clarifications.**
What is the impact on other domains when a grid is created, merged and closed down.
