### ISSUE TITLE
Close down metering point (BRS-007)

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#269]
Description
A grid company initiates this process when they want to close down a metering point. Once the metering point is closed down the GSRN number can no longer be used. Datahub processes the request and either accepts or rejects the message. If the message is approved the metering point is closed down and the balance supplier is informed about the close down.

Acceptance criteria

- [ ] A grid company can request the close down of a metering point
- [ ] A grid company can receive accept/reject messages for their request
- [ ] A balance supplier receives a message when a metering point is closed down (If they are "connected" to the metering point)

The team assesses that it will take 2 developers 1 sprint to complete this feature
