### ISSUE TITLE
(TEST) We can generate an accept message when a request for create X metering point has been accepted

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#288]
**Benefit hypothesis** (Done by PO)
As a grid company
We want to be able to get a reply for our request for create X metering point
So that we know if our request has been approved.

**Description** (Done by PO)
The aim of this user story, is to be able to generate an accept message for the grid companies request for create X metering point, when their request has been approved. 
The grid company needs a reply to know if their request has been approved. 

**Acceptance criteria** (Done by team, is checked off by PO)

- [ ] When a request for create metering point has been approved we are able to reply with an accept message.
- [ ] We reply with an accept message  immediately after approval. Must be within 1 hour after the request has been approved
- [ ] The accept message adheres to relevant CIM format.

**Task** (Done by developers, is checked off by developers)

- [ ] Create ,,,,,

**DoD** (predefined, is checked off by developers and PO)

- [ ] All tasks have been completed (Dev)
- [ ] Has been tested by business (PO/SME)
- [ ] Has been tested by Dev. (Can we be specifc about what tests?)
- [ ] All acceptance criteria are met (Checked of by SME/PO)
- [ ] Solution has been deployed to test environment (Dev)
- [ ] Business/PO has signed off and approved story
- [ ] Solution has been documented (technical doc) 
- [ ] .....

With team I mean everybody in team (PO, SM, Dev and SME)

**Comment by Christian-Meyer** [comment]
Comment about DoD. 
The most important thing for the team is to have a DoD. The aim is not to start off by making a long list. The aim is to come up with a list that ensures quality and to ensure that we with confidence can say that this story is done, and that the requested functionality has been delivered. 
Lets start out with the DoD that we can come up with now, and down the road we can build further upon it. 
Right now we just need some sort of way to now when a story is done.

**Comment by Christian-Meyer** [comment]
This one is closed as it primarily has worked as a template.
