### ISSUE TITLE
Be able to create consumption metering points

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#294]
**Benefit hypothesis**
As a grid company
We want to be able to send in a request to create a consumption metering point, and get our message validated. 
So that we can be informed if our request contains errors.

**Description**
We want to be able to receive a request from a grid company about the creation of a consumption metering point. The purpose of this story is to be able to validate the message and generate either an accept message if the request is approved or a reject message if the request contains errors. 

**Acceptance criteria**
- [x] We can receive a request for create consumption metering point from a grid company
We can perform the following validations:
_Applicable for all MP's_
~- [ ] The physical status of a metering point is mandatory _(error code D02)_ ~ (removed. Put into its own issue)
- [x] The country name of a metering point has domain values DK (Denmark) _(Error code E86)_
- [x] The energy time series measure unit of a metering point is mandatory  _(Error code D02)_
~ - [ ] The meter reading occurrence of a flex-settled or non-profiled settled metering point must be PT1H (også 15 min)  _(Error code D02)_ ~
~- [ ] The meter reading occurrence of a metering point must be PT1H or PT15M  _(Error code D02)_ ~
~ - [ ] The meter reading occurrence of a metering point must be P1M, PT1H or PT15M  _(Error code D02)_ ~
- [x] The kilowatt power limit of a metering point consists of maximal 6 digits  _(Error code E86)_
- [x] The ampere power limit of a metering point consists of maximal 6 digits  _(Error code E86)_
- [x] The location description of a metering point consists of maximal 60 characters  _(Error code E86)_
- [x] The format of the DARReference of the metering point should comply with the generic UUID format  _(Error code E86)_
_For Consumption_
- [x] The first scheduled meter reading date of a metering point is mandatory for a profiled metering point _(Error code D02)_
- [x] The meter number of a metering point consists of maximal 15 characters _(Error code E86)_
~- [ ] Only a Metering Point in group 1 and 2 can act as a parent (i.e. have coupled childs). _(Error code D18)_ ~ (treated in relation with parent/child story)
- [x] The capacity of a metering point consists of maximal 8  characters. Only digits and an optional decimal point are allowed. _(Error code E86)_
- [x] The measure unit must be kWh if the master data does not apply to a metering point of type VE Production (D01), Analysis (D02), Other consumption (D17), Other production (D18), Exchange - Reactive energy (D20) or Internal use (D99)_(Error code E73)_
- [x] If a Consumption metering point (E17) is in net settlement group 1 or 2 then the settlement method must be either Non-profiled (E02) or Flex settled (D01). _(Error code D15)_

- [x] If the request fails one or more validation the request is rejected and a reject message adhering to relevant CIM format is created.
- [x] If the request passes validations an accept message adhering to relevant CIM format is generated and the consumption metering point is created

**Tasks**
- [x] Extract business rules from input validations
- [x] Raise integration event
- [x] Implement missing business rules (See ACs)
- [x] Update CIM formats for aknowledgements

**DoD**
- [x] All tasks have been completed
- [x] All acceptance criteria have been completed
- [x] Unit test performed
~ - [ ] Integration test performed ~
- [x] Tested
- [ ] Accepted by business
- [x] Solution is deployed to test environment

**Comment by Christian-Meyer** [comment]
AC's that have been removed have either been given an issue of its own, or are to be treated in relation with other user stories.
