### ISSUE TITLE
Local postoffice (Part 2)

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#295]
**Benefit hypothesis**
As a grid company
We want to be able to receive messages in relation to create metering point
So that we know what the status is with our request

**Description**
The purpose of this story is to connect our local post office with the main post office created by Titans. A successful outcome is that we are able to receive a request for create metering point and send a response to the grid company through the post office. 

**Acceptance criteria**
- [ ] An accept message can be sent to the grid company
- [ ] A reject message can be sent to the grid company 

**Tasks**
- [ ] 
 
**DoD**

- [ ] All tasks have been completed
- [ ] All acceptance criteria have been completed
- [ ] Unit test performed
- [ ] Integration test performed
- [ ] Tested
- [ ] Accepted by business
- [ ] Solution is deployed to test environment

**Comment by Christian-Meyer** [comment]
Refine together with Titans.
