### ISSUE TITLE
Create grid areas

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#296]
**Benefit hypothesis**
As a grid company
We want to be able to create metering points in existing grid areas. 
So that metering points are created correctly within the right grid area

**Description**
The purpose of this story is to be able to create a set amount of grid areas that contain the correct information for each grid area. 
This means that when creating metering points we are able to use correct grid areas, and we no longer need to simulate grid areas. 

**Acceptance criteria**
- [ ] We have a set amount of grid areas containing the following information: 
     - [x] Grid area name (Length 50 characters)
     - [x] Grid area code (3-digits ex. 007)
     - [ ] Grid operator operator name
     - [ ] Grid operator organisation ID
     - [x] Price area code (length max 5 ex. DK1) 
- [x] The created grids can be used to validate up against the grids stated in request for create metering points
- [x] The model enables merge of grids

**Tasks**
- [x] Set up command, handler, domain model and persistance in processing
Optional
- [ ] Raise integration event through outbox (removed)

**DoD**
- [ ] All tasks have been completed
- [ ] All acceptance criteria have been completed
- [ ] Unit test performed
- [ ] Integration test performed
- [ ] Tested
- [ ] Accepted by business
- [ ] Solution is deployed to test environment

**Comment by Christian-Meyer** [comment]
Integration events have been removed from this story. As other teams are not going to listen to events about grid area created.

**Comment by Christian-Meyer** [comment]
Awaiting confirmation by business.

**Comment by Christian-Meyer** [comment]
Has been reviewed by business, who has accepted the design, and believe that we solve the described problem. We were presented by two new demands which have been separated into their own story. (merge from date and history of changes)
All that remains is accept by software architect
