### ISSUE TITLE
As a grid operator we want to be able to update MP master data on a consumption metering point

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#299]
**Benefit hypothesis**
As a grid company
We want to be able to update metering point master data
So that we can ensure that the data is always up to date

**Description**
It must be possible for a grid company to update metering point master data after a metering point has been created. So once a metering point has been created it should be possible immediately after to update metering point master data. The things in scope for this story is the request from the grid company, validation of the message and accept/reject the request. The information to current and future balance supplier is treated in a separate story. 

**Acceptance criteria**

- [ ] It must be possible for a grid company to send in a request for update metering point master data with business reason _update metering point master data_
- [x] The effective date for change of metering point master data must be the date declared by the grid company and must be todays date or maximum 1 day back in time from todays date.
We must be able to perform the following validations:
- [ ] The grid operator of a metering point must be an existing and active market party (company) on the effectuation date (Error code E01) Alle
- [ ] The reading characteristics of a metering point is mandatory for a profiled metering point (else not allowed, rule is used for updating: element has to be available if changed) (Error code D02)
- [ ] The meter reading occurrence of a metering point is mandatory (rule is used for updating: element has to be available if changed) (Error code D02)
- [ ] The net settlement group of a metering point is mandatory (rule is used for updating: element has to be available if changed) (Error code D02) Change netSettlement group 
- [ ] The power plant of a metering point is mandatory (rule is used for updating: element has to be available if changed) (Error code D57) Specific story 
- [x] The metering point to which the received data applies must be known in the system (Error code E10) Alle
- [x] The metering point to which the received data applies must be owned by the grid operator (Error code E10) Alle
- [x] The data information must be received within the correct time period (Error code E17) Alle
- [x] The metering point to which the received data applies must currently be not closed down (Error code D16) Alle
- [x] The identification of a transaction is mandatory (Error code E0H) Alle
- [x] The Metering Point to which the master data applies must have a registered meter if subtype equals Physical (rule is used for updating: element has to be available if changed) (Error code D31) Metering method
- [x] The Metering Point to which the master data applies cannot have a registered meter if subtype differs from Physical. (Error code 31)
- [x] The connection type of a metering point is mandatory if net settlement group is not 0 (else not allowed, rule is used for updating: element has to be available if changed) (Error code D02)
- [ ] A change of the settlement method is only allowed in case of changing the type of metering point to Consumption (E17) (Error code D15)
- [ ] For a profiled NSG6 metering point the scheduled metering reading date (SMRD01) may not be changed if a change of settlement process (BRS-012) to non-profiled/flex settled is registered in the future. (Error code D47)
- [ ] For a non-profiled/flex NSG6 metering point the scheduled metering reading date (SMRD01) may not be changed (Error code D47)
- [ ] The sub type of a metering point is mandatory (rule is used for updating: element has to be available if changed) (Error code D02) Metering method
- [x] If the request is rejected an reject message is generated and sent to the grid company.
- [x] If the request is approved an accept message is generated and sent to the grid company. 

**Tasks**

 
**DoD**

- [ ] All tasks have been completed
- [ ] All acceptance criteria have been completed
- [ ] Unit test performed
- [ ] Integration test performed
- [ ] Tested
- [ ] Accepted by business
- [ ] Solution is deployed to test environment

**Comment by Christian-Meyer** [comment]
We have talked about keeping event sourcing out of this for now.

**Comment by Christian-Meyer** [comment]
Talk to business about validation rules. 
All rules that are already applicable for create consumption MP are also applicable for update MP master data for a consumption metering point. 
Rules will be updated
