### ISSUE TITLE
A grid company must be able to link a child metering point to a parent metering point

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#301]
**Benefit hypothesis**
As a grid company
We want to be able to create a Dx metering point as a child metering point
So that we can link Dx metering points to parent MP's

**Description**
It must be possible for a grid company to create a Dx metering point as a child metering points and link them to a parent metering point. (Only consumption and production) It is only Dx metering points that can be created as child metering points. A child metering point can be created as a stand alone MP. (with no parent MP)

**Acceptance criteria**

- [x] The Grid Area of a child Metering Point must be the same as its parent (Error code D46)
- [x] A Dx metering point can be created as a stand alone MP and not linked to a parent MP. (This one is probably already solved)
- [x] A child MP can only be coupled to a parent MP when the request is received together with the create child MP request. 
- [ ] <del>The parent of a child metering point must be an existing metering point (error code E10)</del>
- [x] Only a metering point in group 3 and 4 can be a child of 17 and 18 metering point (error code D18)
Group 3 and 4 is all Dx minus D20)

**Tasks**

- [x] Publish integration event to other domains, when a child metering point has been linked to a parent MP
When a special metering point is created we need to sent out an integration event.
- [x] Create a notification handler for SpecialMeteringPointCreated domain event to write to outbox
- [x] Create integration event dispatch handler for special metering points
- [x] Create and Register Topic
- [x] Add Topic to settings (TF)
- [x] Create Topic in servicebus via TF in shared resources project
- [x] Follow up on spillover from PR 483

Spillover from pr 483:
![image.png](https://images.zenhubusercontent.com/60ae3dc186f9224f4cc8b7d8/e5110c0c-11b3-4b0e-95df-f602c29b0a6b)
 
**DoD** (The following are standard DoD steps, feel free to change if necessary) 

- [ ] All tasks have been completed
- [ ] All acceptance criteria have been completed
- [ ] Unit test performed
- [ ] Integration test performed
- [ ] Tested
- [ ] Accepted by business
- [ ] Solution is deployed to test environment
