### ISSUE TITLE
We are able to create production metering points

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#303]
**Benefit hypothesis**
As a grid company
We want to be able to send in a request to create a production metering point, and get our message validated. 
So that we can be informed if our request contains errors.

**Description**
We want to be able to receive a request from a grid company about the creation of a production metering point. The purpose of this story is to be able to validate the message and generate either an accept message if the request is approved or a reject message if the request contains errors. 

**Acceptance criteria**
- [ ] We can receive a request for create production metering point from a grid company
We can perform the following validations:
_Production_
- [x] The meter number of a metering point consists of maximal 15 characters (Error code E86)
- [ ] Only a Metering Point in group 1 and 2 can act as a parent (i.e. have coupled childs). (Error code D18)
- [x] The capacity of a metering point consists of maximal 8  characters. Only digits and an optional decimal point are allowed. (Error code E86)
- [ ] The capacity of a metering point is mandatory if net settlement group is not 0, else optional. (Error code D56)
- [ ] The measure unit must be kWh if the master data does not apply to a metering point of type VE Production (D01), Analysis (D02), Other consumption (D17), Other production (D18), Exchange - Reactive energy (D20) or Internal use (D99) (Error code E73)

- [x] If the request fails one or more validation the request is rejected and a reject message adhering to relevant CIM format is created.
- [ ] If the request passes validations an accept message adhering to relevant CIM format is generated and the production metering point is created

**Tasks**
- [ ] Extract business rules from input validations
- [ ] Raise integration event
- [ ] Implement missing business rules (See ACs)
- [ ] Update CIM formats for aknowledgements

**DoD**
- [ ] All tasks have been completed
- [ ] All acceptance criteria have been completed
- [ ] Unit test performed
- [ ] Integration test performed
- [ ] Tested
- [ ] Accepted by business
- [ ] Solution is deployed to test environment
