### ISSUE TITLE
Be able to to bundle messages (postoffice)

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#325]
**Benefit hypothesis**
As a grid company
We want to be able to receive bundled messages
So that our system if not overloaded with messages

**Description**
The purpose of this story is to be able to bundle messages that are sent from DH to the grid company.
This story does not solve the entire outbound message flow. This story solves that we can bundle certain messages. 
The next step (which is not solved in this story) is to establish the entire outbound message flow.

**Acceptance criteria**
- [ ] Accept messages can be bundled
- [ ] Reject messages can be bundled 

**Tasks**

**DoD**

**Comment by Christian-Meyer** [comment]
![localpostoffice.drawio.png](https://images.zenhubusercontent.com/60bf67953ffc7e5c3e70b6a8/b1b3096d-285d-4ec5-bf14-4469bfaf37d5)

**Comment by Christian-Meyer** [comment]
Titans postoffice flow #215

**Comment by Christian-Meyer** [comment]
@thbaan I have added the following two AC's to highlight that this story is more than just bundling of messages. 
- [ ]Accept messages can be sent individually to grid companies
- [ ] Reject messages can be sent individually to grid companies
Feel free to specify if needed :)

**Comment by Christian-Meyer** [comment]
I have also updated the title, benefit hypothesis and description so it encapsulates what we are doing in this story
