### ISSUE TITLE
Make it possible for the business to test

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#326]
**Benefit hypothesis**
As a business person
We want to be able to test the solution
So that we can validate if everything works accordingly

**Description**
The purpose of this user story is to create a tool that makes it possible for the business to test what has been developed and validate the solution and give feedback. This is the first iteration of the tool. It does not have to be perfect the first time. Once we get feedback we will improve the tool

**Acceptance criteria**
- [ ] The business can send in a request for create metering point
- [ ] The business can view the accept message that is generated if the request is approved
- [ ] The business can view the reject message that is generated if the request is rejected

**Tasks**

**DoD**

**Comment by Christian-Meyer** [comment]
First iteration is time boxed to 5 days.

**Comment by Christian-Meyer** [comment]
@MrDach Can we check some of the boxes off?
