### ISSUE TITLE
Reimplement create consumption metering point event

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#327]
**Benefit hypothesis**
As other teams
We want to be informed when a consumption metering point has been created
So that we can use the information 

**Description**
The purpose of this story is to reimplement what we currently publish when a metering point has been created.
The purpose is to be explicit about what has been created. 
For detailed explanation see https://github.com/Energinet-DataHub/green-energy-hub/blob/main/docs/architecture-decision-record/ADR-0008%20Integration%20events.md

**Acceptance criteria**
- [x] When a consumption metering point has been created the event is published 

**Tasks**
- [x] Create consumption metering point created event
- [x] Update protobuf contracts (See ADR)
- [x] Update Terraform infrastructure
- [x] Inform Joules and Volt about changes
- [x] Update contract MD
- [x] Refactor integration event dispatcher
- [x] Set Metadata on integration events
~- [ ] Setup Squadron for SB test ~ (This one has been skipped for now. A separate task.)

**DoD**
- [x] All tasks have been completed
- [x] All acceptance criteria have been completed
- [x] Unit test performed
- [x] Integration test performed
- [x] Tested
~- [ ] Accepted by business ~
- [x] Solution is deployed to test environment
