### ISSUE TITLE
We can add charges to consumption metering points

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#328]
**Benefit hypothesis**
As a grid company
We want the relevant prices and charges linked to the created metering point
So that we know what prices and charges are applicable 

**Description**
The purpose of this story is to add prices and charges to the created metering point. When the metering point is created we need to add relevant prices and charges to the created the metering point. We need to inform charges about the created metering point and they add prices and charges to created MP. We are then informed about the link.

**Acceptance criteria**
- [x] Consumption metering point event is published
- [ ] Charges are first linked when grid company has received accept message for create consumption metering point
- [ ] When charges are linked MP domain is notified about charge link. 

**Tasks**
- [ ] Make it a long running proces
 
**DoD**

- [ ] All tasks have been completed
- [ ] All acceptance criteria have been completed
- [ ] Unit test performed
- [ ] Integration test performed
- [ ] Tested
- [ ] Accepted by business
- [ ] Solution is deployed to test environment

**Comment by Christian-Meyer** [comment]
@Korgath How do we unblock this? Do others need to do anything?
