### ISSUE TITLE
When metering point master data has been updated the future and current balance supplier is informed about changes.

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#333]
**Benefit hypothesis**
As a current and future balance supplier
We want to be informed about changes to metering point master data made by the grid company
So that we have the most recent and correct data

**Description**
The purpose of this story is to complete the update metering point master data flow by adding the outgoing message that must be sent to future and current balance supplier when metering point master data has been updated. 

**Acceptance criteria**
- [ ] When metering point master data has been updated, a message is sent to the current and future balance suppliers informing them about the update.
- [ ] The information must be sent to the future and current balance supplier no later than 1 hour after the master data has been updated.  
- [ ] When a update metering point master data request is received, and no changes are made, we must still send a master data changed message to current and future balance suppliers.

**Tasks**
- [x] Eksponer events fra market role. E.g. energy supplier registrered, changed
- [x] Infrastructure
  - Nye topics
  - Subscriptions
- [x] Subscribe on events received from market role
- [x] Data model der kan håndtere el leverandør forhold
- [x] Domæne model der kan håndtere el leverandør forhold
- [x] Command der kan opdatere el leverandør forhold
- [ ] Dannelse af besked (RSM-022)
- [x] logik til håndtere af udsendelse til nuværende og fremtidige elleverandører (husk transaction bøvl)
- [x] Query alt data for MP til besked der skal udsendes
- [ ] <del>Listen to effectuate and annullment integration events</del>

Missing:
- Roles for market participants. From MR?
- "Actor Register"
- Grid operator GLN
- NextReadingDate
- Parent/Child
- Line endings/encoding/BOM?
 
**DoD**

- [ ] All tasks have been completed
- [ ] All acceptance criteria have been completed
- [ ] Unit test performed
- [ ] Integration test performed
- [ ] Tested
- [ ] Accepted by business
- [ ] Solution is deployed to test environment

**Comment by MrDach** [comment]
Future suppliers might be "simulated" by setting multiple suppliers back in time since they're handled relative to each other.
E.g. if the current date is the 30th and we request supplier changes on the 25th and 26th then the one on the 26th will be considered being in the future. See Ermins excellent diagram for further explanation:

![MicrosoftTeams-image (4).png](https://images.zenhubusercontent.com/60ae851046d844cc53495e6f/3d9ed041-7ff7-4861-af80-670eb461b40f)

**Comment by erduna** [comment]
Energy suppliers are not added in the "EnergySuppliers" table in MP domain.
