### ISSUE TITLE
As a grid operator we want to be able to update MP master data on an exchange metering point

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#342]
**Benefit hypothesis**
As a grid company
We want to be able to update metering point master data
So that we can ensure that the data is always up to date

**Description**

**Acceptance criteria**

- [ ] It must be possible for a grid company to send in a request for update metering point master data with business reason _update metering point master data_
- [ ] The effective date for change of metering point master data must be the date declared by the grid company and must be todays date or maximum 1 day back in time from todays date.
We must be able to perform the following validations:
- [ ] It is not allowed to provide the source metering grid area if a metering point of type is Exchange - Reactive energy (D20). (Error code D46)
- [ ] It is not allowed to provide the target metering grid area if a metering point of type is Exchange - Reactive energy (D20). (Error code D46)
- [ ] It is not allowed to update the source metering grid area when the type of metering point is Exchange (E20) (Error code D46) Exchange
- [ ] It is not allowed to update the target metering grid area when the type of metering point is Exchange (E20) (Error code D46) Exchange
- [ ] If the request is rejected an reject message is generated and sent to the grid company.
- [ ] If the request is approved an accept message is generated and sent to the grid company. 

**Tasks**
- [ ] 
 
**DoD**
This is a general set of definition of done steps. Not all have to apply for each story. Discuss which one of them apply for each individual story. 

- [ ] All tasks have been completed
- [ ] All acceptance criteria have been completed
- [ ] Unit test performed
- [ ] Integration test performed
- [ ] Tested
- [ ] Accepted by business
- [ ] Solution is deployed to test environment
