### ISSUE TITLE
En netvirksomhed skal kunne oprette og vedligeholde målepunkter med tilhørende priser og kommunikation

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#520]
**Benefit hypothesis**
As a grid company
We want to be able to create, update and connect metering points and receive responses for our requests
So that metering points can be used, updated and are ready to be billed. 

**Description**
A grid company must be able to create, maintain, and connect metering points and receive answers for their requests. 
This feature also add basic security and schema validation for incoming requests.
When this feature is completed it enables the grid company to participate in the February test. Were they can test metering point processes and the new CIM/JSON format.  

**Acceptance criteria**

**Basic security & B2B endpoint protection, Authentication (B2B & GUI)​​**
**Login**
- [x] Create login screen and use layout from [prototype]((https://www.figma.com/proto/5lCd6Wq5bcDkOXIMgyLST6/DataHub-3.0?page-id=562%3A2395&node-id=720%3A6058&viewport=241%2C48%2C0.15&scaling=contain&starting-point-node-id=720%3A6058&show-proto-sidebar=1))
- [x] Authenticate user ([look here]((https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-angular-auth-code)) and [here]((https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular)))
- [x] Redirect to log in page if user is not authenticated and tries to reach any link (eg. search metering point)
- [x] All user within an actor have same access (we don't have multiple roles with different access policies)

**B2B**
- [x] Remove gate policy so that `main` is always deployed to `IT-LEV` (environment for actor testing)
- [x] Move `greenforce-frontend` to new azure subscription
- [x] Update `greenforce-frontend` to use new TF modules

**Basic security**
- [x] ~~DNS is setup for `B002`~~
- [x] ~~VNET is added to `Shared Ressources`~~
- [x] ~~VNET is added to `metering-point domain`~~
- [x] ~~VNET is added to `market-roles domain`~~
- [x] ~~VNET is added to `post-office domain`~~
- [x] ~~VNET is added to terraform module for `SQL server`~~
- [x] ~~VNET is added to terraform module for `Service Bus`~~
- [x] ~~VNET is added to terraform module for `Storage Account`~~
- [x] ~~VNET is added to terraform module for `Function Application`~~
- [x] Connect API Management and Application Insights

**Receive messages**
- [x] Be able to log messages​

**Schema validate received RSM-messages (RSM021) with informative error responses ​**
- [x] Schema validate create MP 
- [x] Schema validate update MP
- [x] Schema validate connect MP

**Actor management**
- [x] Implement actor register in domain

**Finish create metering point​**
   - [x] Være i stand til at sende til korrekt modtager​​
   - [x] Validering på om afsender af request må foretage handlingen​​

**Finish update metering point**
  - [x] Be able to update a consumption metering point
  - [x] Be able to update a production metering point
  - [x] Be able to update an exchange metering point
  - [x] Be able to update Dx metering points
  - [x] Be able to send an accept/reject response to correct recipient ​​
  - [x] Validate if requester is able to perform the action​​

**Finish connect metering point**
  - [x] Connect production MP
  - [x] Connect exchange  MP
  - [x] Connect Dx MP types
  - [x] Be able to send an accept/reject response to correct recipient ​​
  - [x] Validate if requester is able to perform the action​​

**Skærmbillede til fremsøg & vis målepunkt** 
- [x] Retrieve and show primary master data information for consumption, production and exchange **MD has a PR**
- [x] Retrieve and show secondary master data information consumption, production and exchange
- [x] Create child metering point overview table
- [x] Retrieve and show primary master data information for child metering points
- [x] Retrieve and show secondary master data information for child metering points
- [x] Add identity + hardcoded breadcrumbs for child metering point
- [x]  Add identity + hardcoded breadcrumbs for Metering point **MD has a Draft PR**

**Comment by Christian-Meyer** [comment]
@mknic The open stories from MD on this feature, are they still open?

**Comment by mknic** [comment]
@Christian-Meyer they are now moved to `closed`.

**Comment by Christian-Meyer** [comment]
@mogensjuul This is done and ready to be closed

**Comment by Christian-Meyer** [comment]
All AC's completed - Check
All tasks completed - Check
Unit and integration tests - Check
Integrated in release pipeline - Check
