### ISSUE TITLE
We want to ensure that only authorized actors are able to access and perform actions in the system

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#538]
**Benefit hypothesis**
As a grid company
We only want to be able to perform certain actions in the system
So that we can only perform actions regarding metering points we own

**Description**

We want to ensure that only permitted actors are allowed to perform actions regarding metering points. 
This means that we need to be able to receive a token that is received together with the request and carry it through the system. The token contains information that is needed to determine if they are allowed to perform the action and in order to send the response to the correct recipient. 

**Acceptance criteria**

- [ ] A grid company can only access the system if they have been authorized 

**Tasks**
- [ ] Implement token functionality
- [ ] JWT deserializer middleware
