### ISSUE TITLE
Create relation between grid company and grid area

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#539]
**Benefit hypothesis**
As a grid company
We must only be able to create  and maintain metering points in grid we own
So that other grid companies cannot create and maintain metering points in grid they do not own. 

**Description**
We want to be able to determine if the actor in the received request is allowed to perform the action they are requesting in the requested grid. In order to do so we need to create a relation between grid areas and grid operators.

**Acceptance criteria**
- [ ] A grid company can only create and maintain metering points in grids they own

**Tasks**
- [ ] Create model for grid company
- [ ] Create relation between actor and grid area
- [ ] Seed data
