### ISSUE TITLE
We want to be able to determine if the actor is allowed to perform a create metering point in requested grid

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#540]
**Benefit hypothesis**
We want to ensure that only actors that are allowed to perform actions in the requested grid are able to do so.

**Description**
We want to make sure that the actor is allowed to perform the requested action in the grid area from their request.
This is a validation rule that checks if they allowed to do so. If not a reject message is generated

**Tasks**

- [ ] Create Business Rule
  - 
- [ ] Create Grid Company Repository
- [ ] Apply business rule in relevant handlers  for implemented processes

**Acceptance criteria**
- [ ] If a grid company owns the grid they are allowed to create metering points
- [ ] If a grid company does not own the grid they are denied, and a reject message is generated
