### ISSUE TITLE
Revisit accept/reject messages

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#541]
**Benefit hypothesis**
As a grid company
We want to be able to receive accept/reject messages
So that we know the status of our request

**Description**
We need to make sure that accept/reject messages adhere to the CIM XML format. Furthermore we need to change hardcoded values in the message to make sure that the message is received by the correct recipient.

**When looking at this, revisit dependency linked to story and see if issues are fixed together with this and if they can be dealt with now.** 

**Acceptance criteria**
- [ ] A grid company must be able to receive an accept/reject for their request

**Tasks**
- [ ] Replace hardcoded values
- [ ] Validate outgoing message (with tests)

**Comment by Christian-Meyer** [comment]
Story is blocked until we have implemented token and actor
