### ISSUE TITLE
Change MP created event from 4 events to one single event

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#545]
**Description**
As we are changing the model for handling metering points from four to one, we will change the metering point created events from four to one event. 
The plan is to keep the single metering point created events running until teams have implemented the new event in their domains.
We need to define a new contract and implement the functionality in the MP domain.

**Acceptance criteria**
- [ ] When a metering point is created an event is generated that other domains can listen to. 

**Tasks**
- [ ] Define contract 
- [ ] Implement functionality
- [ ] Update with metadata
- [ ] Update smoke tests
