### ISSUE TITLE
As a grid company we want to be able to change the connection status of a metering point.

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#630]
**Benefit hypothesis**
As a grid company
We want to be able to change the connection status of a metering point to either disconnected or connected and close down metering points
So that we can either stop the connection, reconnect it or close down.

**Description**
A grid company should be able to change the connection status of metering points they own and close them down

**Acceptance criteria**
- [x] A grid company can send in a request for change connection status
- [x] A grid company can send in a request for close down metering point
- [x] It is possible for at grid company to close down a metering point
- [x] It is possible for at grid company to change the connection status of a metering point they own
- [x] A grid company can receive a accept/reject message for their change connection status request
- [x] A grid company can receive a accept/reject message for their change close down MP request
- [x] A balance supplier is informed when changes to connection status occur. (can first be tested once balance suppliers are connected to system
- [x] Update frontend to show new connection status. From connected --> Disconnected --> connected

**Comment by Christian-Meyer** [comment]
@mknic I have identified a few frontend tasks that might need some updating of the design system and prototype.
The frontend should be able to show the following: 
Update frontend to show new connection status. From connected --> Disconnected --> connected
Update frontend to show metering point is closed down. This means that some data is no longer shown in frontend for the specific metering point
