### ISSUE TITLE
Metering point process overview 

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#679]
**Benefit hypothesis**
As a grid company
We want to be able to see the status of our processes in the GUI
So that we know what the status is of each process. 

**Description**
This story is about the backend functionality needed to show the process overview for metering point in the GUI together with the preliminary work needed for the backend. The frontend work is done in separate stories.   

**Acceptance criteria**
- [x] It is possible to show metering point created in process overview together with received date and valid from date and status of the transaction
- [x] It is possible to show metering point connected request in process overview together with received date and status of transaction 
- [x] It is possible to show if request metering point connect has been rejected together with validation errors and received date and status of transaction 
- [x] It is possible to show if request metering point connect has been accepted together with validity from date and status of transaction. 
- [x] It is possible to see if request MP update message has been received 
- [x] It is possible to see if request MP update request has been approved with received date and active from date. 
- [x] It is possible to see if request MP update has been rejected together with validations that have failed.
- [ ] ~~It must be possible to view if messages have been dequeued.~~

**Tasks**
- [x] Create read model (separate table in DB) with query placed in application layer
- [x] Create temporary solution to populate data from read source. By putting a handler on command pipeline which is limited to IBusinessRequest. So that read model is updated in same transaction as for write operation. 

**Info about message status.**
When a request has been received it has status "modtaget"
When a request has been accepted it has status "Afsluttet"
When a request has been rejected is has status "Afsluttet"
The status "afsluttet" is used to show that the transaction has been completed. A rejection is also viewed as completed. 
The business also wants to be able to see when a message has been dequeued by the actor, this is used as part of their work.  So there is a need to view when messages have been dequeued by the actor.
